#include "stm32l0xx_hal.h"
#include "prototypes.h"
#include "config.h"



void setLED(led LED)
{
	switch (LED)
	{
	case LED_9:
		HAL_GPIO_WritePin(LED3_PORT, LED3_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDA_PORT, LEDA_PIN, GPIO_PIN_RESET);
		break;
	
	case LED_8:
		HAL_GPIO_WritePin(LED2_PORT, LED2_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDA_PORT, LEDA_PIN, GPIO_PIN_RESET);
		break;

	case LED_7:
		HAL_GPIO_WritePin(LED1_PORT, LED1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDA_PORT, LEDA_PIN, GPIO_PIN_RESET);
		break;

	case LED_6:
		HAL_GPIO_WritePin(LED3_PORT, LED3_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDB_PORT, LEDB_PIN, GPIO_PIN_RESET);
		break;

	case LED_5:
		HAL_GPIO_WritePin(LED2_PORT, LED2_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDB_PORT, LEDB_PIN, GPIO_PIN_RESET);
		break;

	case LED_4:
		HAL_GPIO_WritePin(LED1_PORT, LED1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDB_PORT, LEDB_PIN, GPIO_PIN_RESET);
		break;

	case LED_3:
		HAL_GPIO_WritePin(LED3_PORT, LED3_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDC_PORT, LEDC_PIN, GPIO_PIN_RESET);
		break;

	case LED_2:
		HAL_GPIO_WritePin(LED2_PORT, LED2_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDC_PORT, LEDC_PIN, GPIO_PIN_RESET);
		break;

	case LED_1:
		HAL_GPIO_WritePin(LED1_PORT, LED1_PIN, GPIO_PIN_SET);
		HAL_GPIO_WritePin(LEDC_PORT, LEDC_PIN, GPIO_PIN_RESET);
		break;
	}
}

void clearLEDs()
{
	HAL_GPIO_WritePin(LED1_PORT, LED1_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED2_PORT, LED2_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LED3_PORT, LED3_PIN, GPIO_PIN_RESET);
	HAL_GPIO_WritePin(LEDA_PORT, LEDA_PIN, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LEDB_PORT, LEDB_PIN, GPIO_PIN_SET);
	HAL_GPIO_WritePin(LEDC_PORT, LEDC_PIN, GPIO_PIN_SET);
}